services:
  postgres:
    image: postgres:16
    container_name: events-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: events_db
    volumes:
      - ./src/main/resources/db/changelog:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"