apiVersion: v1
kind: ConfigMap
metadata:
  name: ng-events-backend-config
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/config: {{ .Values.config | toJson | sha256sum }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}