apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-events-deployment
  labels:
    app: ng-events-backend
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: ng-events-backend
  template:
    metadata:
      labels:
        app: ng-events-backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.role | default "ng-backend-dev" }}"
        vault.hashicorp.com/service: "{{ .Values.vault.addr | default "http://host.docker.internal:8200" }}"
        vault.hashicorp.com/auth-path: "{{ .Values.vault.authPath | default "auth/kubernetes" }}"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-config.properties: "{{ .Values.vault.secretPath | default "kv/data/ng-events/backend" }}"
        vault.hashicorp.com/agent-inject-template-config.properties: |
          {{`{{- with secret "kv/data/ng-events/backend" -}}`}}
          SPRING_DATASOURCE_USERNAME={{`{{ .Data.data.SPRING_DATASOURCE_USERNAME }}`}}
          SPRING_DATASOURCE_PASSWORD={{`{{ .Data.data.SPRING_DATASOURCE_PASSWORD }}`}}
          APP_JWT_SECRET={{`{{ .Data.data.APP_JWT_SECRET }}`}}
          {{`{{- end }}`}}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "ng-backend.fullname" . }}-sa
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.containerPort | default 8080 }}
          {{- if .Values.envFrom.configMapRef }}
          envFrom:
            {{- if .Values.envFrom.configMapRef }}
            - configMapRef:
                name: {{ .Values.envFrom.configMapRef }}
            {{- end }}
          {{- end }}
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/vault/secrets/config.properties"
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath | default "/actuator/health" | quote }}
              port: {{ .Values.containerPort | default 8080 }}
            initialDelaySeconds: {{ .Values.probes.initialReadinessDelay | default 10 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath | default "/actuator/health" | quote }}
              port: {{ .Values.containerPort | default 8080 }}
            initialDelaySeconds: {{ .Values.probes.initialLivenessDelay | default 30 }}
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
      terminationGracePeriodSeconds: 30