apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-events-backend-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: ng-events-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ng-events-backend
  template:
    metadata:
      labels:
        app: ng-events-backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.role }}"
        vault.hashicorp.com/service: "{{ .Values.vault.addr }}"
        vault.hashicorp.com/auth-path: "{{ .Values.vault.authPath }}"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-config.properties: "{{ .Values.vault.secretPath }}"
        vault.hashicorp.com/agent-inject-template-config.properties: |
          {{`{{- with secret "kv/data/ng-events/backend" -}}`}}
          SPRING_DATASOURCE_USERNAME={{`{{ .Data.data.SPRING_DATASOURCE_USERNAME }}`}}
          SPRING_DATASOURCE_PASSWORD={{`{{ .Data.data.SPRING_DATASOURCE_PASSWORD }}`}}
          APP_JWT_SECRET={{`{{ .Data.data.APP_JWT_SECRET }}`}}
          {{`{{- end }}`}}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "ng-backend.fullname" . }}-sa
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: ng-events-backend-config
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/vault/secrets/config.properties"
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath | quote }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.initialReadinessDelay }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath | quote }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.initialLivenessDelay }}
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
      terminationGracePeriodSeconds: 30