apiVersion: v1
kind: Service
metadata:
  name: events-backend-service
  namespace: ng-events
  labels:
    app: ng-events-backend
spec:
  type: ClusterIP
  selector:
    app: ng-events-backend
  ports:
    - name: http
      port: {{ default 80 .Values.service.port }}
      targetPort: {{ default 8080 .Values.service.targetPort }}