image:
  repository: host.docker.internal:5001/ng-proovitoo-backend
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-regcred

replicaCount: 1
containerPort: 8080

envFrom:
  configMapRef: ng-events-backend-config

service:
  port: 80
  targetPort: 8080

probes:
  readinessPath: /actuator/health
  livenessPath: /actuator/health
  initialReadinessDelay: 10
  initialLivenessDelay: 30

ingress:
  enabled: false          
  ingressClassName: nginx
  host: ""                
  apiPrefix: /api/?(.*)

vault:
  addr: "http://host.docker.internal:8200"
  authPath: "auth/kubernetes"
  role: "ng-backend-dev"
  mode: "prepopulate"
  secretPath: "kv/data/ng-events/backend"

config:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5436/events_db?currentSchema=event_mgmt"
  SPRING_LIQUIBASE_DEFAULT_SCHEMA: "event_mgmt"
  SPRING_LIQUIBASE_LIQUIBASE_SCHEMA: "liquibase"
  SPRING_LIQUIBASE_ENABLED: true

  APP_JWT_ISSUER: "events-app"
  APP_JWT_EXPIRY_MINUTES: 60

  APP_COOKIES_NAME: "access_token"
  APP_COOKIES_HTTP_ONLY: true
  APP_COOKIES_SECURE: false
  APP_COOKIES_SAME_SITE: "Lax"
  APP_COOKIES_MAX_AGE_MINUTES: 60